### ISSUE TITLE
Add basic large sequence processing capabilities

### ISSUE THREAD

**Issue by fingerx** [unity3d-jp/StreamingImageSequence#70] opened 2020-05-22 07:20 UTC
When the sequence frames are greater than 1000 [my actual projects are basically 5000 to 20,000 frames], I want to do dynamic loading and unloading, and add dynamic caching mechanism.
Without these basic features, this project is just a toy.

There is some discussion below this, and of course we can also use a third party HAP.
https://forum.unity.com/threads/frame-accurate-video-or-image-sequence-playback.854203/

**Comment by sindharta** [comment] 2020-05-22 09:50
The images are automatically loaded when playing the Timeline window, and they are cached.

It seems that you want to manually load/unload the images (via scripts maybe ?).
Can you elaborate why, and share your use case ?

**Comment by fingerx** [comment] 2020-05-23 15:28
thanks. I want to play the frame-based sequences in real time to replace the video with them. Because the video is inaccurate. As discussed in the UNITY forum, we need a frame-based sequence player. If it could be frame-based, then it would be of great use in projection engineering and film. Such a feature is not easy, at the moment I test the latest version and basically get stuck and can't do anything, I have a large number of serial frames.

**Comment by fingerx** [comment] 2020-05-23 15:34
my test pc is win10

System architecture: Intel CPU Family:6, Model:15, Stepping:1 with MMX, SSE Integer, SSE FP, SSE2, SSE3, SSE4.1, SSE4.2, HyperThreading
Physical processor count: 10
Logical processor count: 20
Processor speed: 2195 MHz
Built-in memory: 16305 MB
Free memory: 9833 MB
Video Card Vendor: NVIDIA Corporation
Video Card Renderer: Quadro M2000/PCIe/SSE2
Display: 1
Display Bounds:=  top: 0, left: 0, bottom: 1440, right: 2560 
Video Card Number: 1
Video Card: NVIDIA Quadro M2000

**Comment by sindharta** [comment] 2020-05-25 02:18
> I test the latest version and basically get stuck and can't do anything.

Can you post a picture or a video showing that you are stuck ?
Have you checked the [tutorial](https://docs.unity3d.com/Packages/com.unity.streaming-image-sequence@0.1/manual/en/StreamingImageSequencePlayableAsset.html) ?

**Comment by fingerx** [comment] 2020-05-25 13:24
yes, i checked turorial.I will provide pictures or video later.

**Comment by fingerx** [comment] 2020-05-25 15:16
![Snipaste_2020-05-25_23-08-06](https://user-images.githubusercontent.com/5524551/82825417-cb0fe900-9edd-11ea-8d3e-99bef476b7e4.png)
![Snipaste_2020-05-25_23-15-42](https://user-images.githubusercontent.com/5524551/82825423-cd724300-9edd-11ea-86b7-21dc9d33e8de.png)

**Comment by sindharta** [comment] 2020-05-26 13:04
If you have 9000 4K textures on a PC with 16 GB memory, then yes, currently it will cause out of memory and will probably crash.

The reason we try to load almost all the textures dynamically is that we want to show the textures immediately by dragging the time in the timeline window. 
Loading images one by one as we slide the time will cause disruption in the user's workflow, and because a user can slide the time in the timeline window however they want, it is not possible to predict the next image that a user wants to see, and avoiding this disruption is our top priority at the moment.

That said, we understand your concern and will put a task to improve our resource management system in our backlog.

In the meantime though, you can divide your images into a couple of scenes to reduce memory usage, or perhaps get larger memory for your computer.

We do have an internal API to unload all textures (executable from menu: Assets/Streaming Image Sequence/Reset). This is not public, but I think we can easily open the API if this is something that you want to use to organize resource loading by yourself at the moment.

**Comment by fingerx** [comment] 2020-05-27 09:42
Thank you very much for the advice. It seems I can only buy more memory for now.
 But I also want you to consider that there are actually two general directions of application, one that requires timeline based previews in the movie. One might just need to be precise based on the frame to be able to play smoothly, pause. 
Another problem is the inability to cut scenes most of the time, and at the moment it seems that only more memory can be purchased. 
Although it's not a good way to go about it. But that may be the only way to go for now. Thanks again.

**Comment by sindharta** [comment] 2020-06-12 02:36
This has been fixed in released as part of version 0.2.0-preview.
Please check and feel free to reopen this issue if you are still able to reproduce this issue.

**Comment by fingerx** [comment] 2020-06-13 16:56
It's better than before, but still has the same problem, it doesn't work in unity. Use the images I mentioned before. If you can provide me with your email address, I can send you the test material in the next few days. You can try.

**Comment by sindharta** [comment] 2020-06-15 03:36
Reopening this issue. 
@fingerx Would it be possible for you to upload your data somewhere so that we can download it ?

Some alternatives that I can think:
1. Use cloud service (such as Google Cloud Drive) to store a zip containing the files, and put the link here.
2. Upload your test data to a new repo on github and give me (sindharta) access
3. If your test data contains confidential information, perhaps you can let us know where to contact you. That way, a member of our team would be able to reach out to you.

**Comment by fingerx** [comment] 2020-06-15 14:07
I'll upload the test data later and let you know the download link. The data is very large and may take time to upload. This data can be used for testing, but not publicly available. Also I have serial data from many projects that are available for testing. This includes different resolutions and different formats. I can provide this if needed.

**Comment by sindharta** [comment] 2020-06-16 02:34
@fingerx  That sounds good. Please let us know once you have finished uploading those data.

**Comment by fingerx** [comment] 2020-06-16 10:28
please send me your email to pxcoder@gmail.com, i will send your download link.

**Comment by fingerx** [comment] 2020-06-17 10:47
@sindharta Please check your email, I've sent the download link.

**Comment by fingerx** [comment] 2020-06-20 03:59
@sindharta  want to know any good news?

**Comment by sindharta** [comment] 2020-06-21 02:07
@fingerx We are focusing on other stuffs right now and will come visit this issue again very soon.
So, at the moment, not yet.

**Comment by fingerx** [comment] 2020-07-03 02:46
@sindharta 
It's been about two weeks. Can you tell me some basic information? Thank you

**Comment by sindharta** [comment] 2020-07-03 07:45
@fingerx This issue is one of the things that we are currently working on right now.

**Comment by sindharta** [comment] 2020-07-14 07:00
@fingerx We have released version 0.3.0-preview, which prevents crash due to over memory usage, and improves the image loading speed compared to the earlier version.

**Comment by fingerx** [comment] 2020-07-14 07:18
@sindharta  thanks,I will test it in detail and let you know the results.

**Comment by fingerx** [comment] 2020-07-14 08:17
@sindharta 
First of all, thank you very much for your efforts, the current version of the operation does not take up all the memory, the computer does not crash. But there is a problem with the smooth playback. The frame rate is very low. Please see the pictures I provided. I have the laptop configuration win10 pro,16g ram,p3200 gpu,cpu i7- 8750H@2.20GHz,intel 660p ssd 

![Snipaste_2020-07-14_16-09-17](https://user-images.githubusercontent.com/5524551/87401877-54de5780-c5ed-11ea-9d06-a04faa2d7a44.png)

**Comment by sindharta** [comment] 2020-07-14 10:03
Unfortunately, with the data that you have (9081 4K textures), and your machine specs (16GB RAM), you would have to do some workarounds to achieve smooth playback, because:

1. Loading one 4K image itself takes around 500 ms - 1000ms on SSD. 
To achieve smooth playback without previously loading the image in memory, we need this to be less than 33 ms (for 30 fps). 

2. One 4K png image occupies 32 MB on memory. With 500 images, that's already 16 GB.


If we can cache all the images in memory, then we can avoid the image loading speed problem. So, there are several alternatives that you can do, depending on your needs:

- Decrease the resolution of the image
- Increase the memory of your machine
- Split your images into several folders, and make one folder contain 200-300 images, so that they will show as different TimelineClips in TimelineWindow

**Comment by fingerx** [comment] 2020-07-14 16:10
First of all, thank you very much for your suggestions. I have some ideas.

1. If using the original image loading does take a lot of time. I suggest to use c++ to read dds files through unity native plugins. You can check this example https://github.com/hecomi/UnityCustomTextureUpdateForDXT1
2. You say "One 4K png image occupies 32 MB on memory. With 500 images, that's already 16 GB." From one aspect, this is a wrong way. What we need is streaming dynamic loading and unloading, not putting All data is put into memory. For example, a 32Gb hap encoded video file. A good example is that you can check vray's product pdplayer, which is a sequence frame player.

At present, I will not use this product for actual projects. I am only very interested in it, because unity has never really been used in actual production of sequence players. Thanks again.

**Comment by sindharta** [comment] 2020-07-15 03:06
For our current goals, we are not considering to use DDS, primarily because:

1. The file size might be bigger
2. The image quality is worse, because DDS uses DXT compression, which is lossy
3. DDS is DirectX only

I believe I have mentioned the above reasons to you in  #@69

>  What we need is streaming dynamic loading and unloading

Sure, that will work if the speed of loading each image is faster than 33 ms, which isn't the case. That's why we need to load them in memory to achieve smooth playback.

It's unfortunate that this package doesn't seem to cater to your needs. 
We are developing this package with the anime/film industry as our main target audience, and I really appreciate that you gave us these test images, which have proven very useful/inspiring for improving the overall quality of the package.

**Closed by sindharta** 2020-07-15 03:06 UTC

**Comment by fingerx** [comment] 2020-07-15 18:04
vray's product pdplayer is for anime/film industry.The dds format does not work on current mac. However, the dds format has too many advantages on windows. I tried to write a sequence player that can play 4k sequences smoothly on the same windows hardware. Thank you for all your help.
![Snipaste_2020-07-16_02-03-08](https://user-images.githubusercontent.com/5524551/87579552-acbdb100-c708-11ea-9b82-0d0f1b31be0a.png)
![Uploading Snipaste_2020-07-16_02-03-48.png…]()

**Comment by sindharta** [comment] 2020-07-16 01:04
I would be interested to know how you are loading those dds images in Unity, to see if there is anything that may help us in improving the package further, if it's possible for you to share the source.
